name: deploy.yml
on:
  push:
      branches:
        - main

jobs:
  deploy:
      runs-on: self-hosted
      steps:
        - name: Checkout
          uses: actions/checkout@v3.0.0
        - name: Build Docker
          run: docker build -t go-app .
        - name: Stop Container
          run: |
            docker stop go-app || true
            docker rm go-app || true
        - name: Run Container
          run: docker run -d -p 8080:8080 --name go-app go-app
